name: CI
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read # for actions/checkout to fetch code
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.24"
      - name: Install yamlfmt
        run: go install github.com/google/yamlfmt/cmd/yamlfmt@v0.17.2
      - uses: flowexec/action@v1
        with:
          executable: 'validate'
          timeout: '5m'
          flow-version: 'main'
